FROM php:7.4-fpm-alpine as builder

RUN apk add --no-cache openssl bash mysql-client
RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /var/www
RUN rm -rf /var/www/html 

COPY . /var/www/
RUN composer install \
    && php artisan config:cache \
    && chmod -R 777 storage

RUN ln -s public html

EXPOSE 9000

ENTRYPOINT ["php-fpm"]
